"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-10

Creates every table from app.models. Uses metadata.create_all() rather
than hand-written op.create_table() calls so the migration can never drift
out of sync with the ORM models it was generated from. Subsequent schema
changes should be added as normal autogenerated revisions on top of this
one (`alembic revision --autogenerate -m "..."`).
"""
from alembic import op

from app import models  # noqa: F401 - registers all tables on Base.metadata
from app.database import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
